Supplier.create!(name: "Bruce Lee", email: "bl@gmail.com", phone_number: "312-454-5454")
Supplier.create!(name: "Aaron Rodgers", email: "AAron@gmail.com", phone_number: "920-878-0890")

Product.create!(name: "Red Orchid", price: 65, description: "It is red and it is an orchid.", supplier_id: 1)
Product.create!(name: "Hemp", price: 60, description: "This plant smells a little funny.", supplier_id: 1)
Product.create!(name: "Dandelion", price: 0.25, description: "You really shouldn't pay us for this. Just go to your local park.", supplier_id: 2)
Product.create!(name: "Black Eyed Susans", price: 35, description: "Wildflower. Pretty cool.", supplier_id: 1)
Product.create!(name: "Pothos Plant", price: 20, description: "Plant grows like weeds. Does not like too much sun.", supplier_id: 2)

Image.create!(product_id: 1, url: "http://www.hotel-r.net/im/hotel/asia/in/red-orchid-1.jpg")
Image.create!(product_id: 2, url: "https://images.axios.com/o0uV3tSZDFAHCNKKphGJcQAAt6E=/0x138:5079x2995/1920x1080/2018/12/21/1545391645683.jpg")
Image.create!(product_id: 3, url: "https://cdn1.medicalnewstoday.com/content/images/hero/324/324083/324083_1100.jpg")
Image.create!(product_id: 6, url: "https://www.edenbrothers.com/store/media/Seeds-Flowers/resized/SFBLA111-1_medium.jpg")
Image.create!(product_id: 7, url: " https://s3-us-west-1.amazonaws.com/landgbucket/products/prod_NqKE50Q71ldgBL/main-alt.jpg")
Image.create!(product_id: 7, url: "https://secure.img2-fg.wfcdn.com/im/64104621/compr-r85/1657/16576772/artificial-real-touch-pothos-hanging-plant-in-square-basket.jpg")
Image.create!(product_id: 7, url: "https://q7i2y6d5.stackpathcdn.com/wp-content/uploads/2010/02/pothos1-400x533.jpg")
